"""Fix phone no field

Revision ID: 077cd8d76fe8
Revises: 115ca6bfa597
Create Date: 2025-03-31 12:12:54.270735

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '077cd8d76fe8'
down_revision = '115ca6bfa597'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hostel', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_number', sa.String(length=15), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hostel', schema=None) as batch_op:
        batch_op.drop_column('phone_number')

    # ### end Alembic commands ###
