"""Added description and phone no field

Revision ID: 115ca6bfa597
Revises: c9d758bc0690
Create Date: 2025-03-31 12:06:31.118579

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '115ca6bfa597'
down_revision = 'c9d758bc0690'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hostel', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hostel', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
