"""Add vacancies to Hostel

Revision ID: c9d758bc0690
Revises: 2a6a5b93a9ed
Create Date: 2025-03-28 22:00:48.410882

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9d758bc0690'
down_revision = '2a6a5b93a9ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hostel', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vacancies', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hostel', schema=None) as batch_op:
        batch_op.drop_column('vacancies')

    # ### end Alembic commands ###
